spring.config.import=optional:file:.env[.properties]

spring.application.name=api
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.error.include-message=always
server.error.include-binding-errors=always